name: rpl_lab
include:
  # Workcells
  - workcells/rpl_modular_workcell/rpl_modular_workcell.compose.yaml
  - dashboard/dashboard.compose.yaml
  # - workcells/n9_workcell/n9_workcell.compose.yaml
  # - workcells/mir_mobile_workcell/mir_mobile_workcell.compose.yaml
services:
  # Single Redis used by whole lab
  rpl_redis:
    image: redis
    container_name: rpl_redis
    ports:
      - 6379:6379
    volumes:
      - ~/.wei/redis:/data
    command: redis-server --save 60 1 --loglevel warning

################
# Data Storage #
################
volumes:
  diaspora_config:
    driver: local
