name: rpl_lab
include:
  # Workcells
  - workcells/rpl_modular_workcell/rpl_modular_workcell.compose.yaml
  # - workcells/n9_workcell/n9_workcell.compose.yaml
  # - workcells/mir_mobile_workcell/mir_mobile_workcell.compose.yaml
  # Applications
  - applications/squid_app/squid_app.compose.yaml
services:
  # Single Redis used by whole lab
  rpl_redis:
    image: redis
    container_name: rpl_redis
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DIR}:/data
    command: redis-server --save 60 1 --loglevel warning
  # Redis Commander for viewing lab state in browser
  # Go to http://localhost:8081 to access
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:rpl_redis:6379
    depends_on:
      - rpl_redis
  # Attachable terminal container with WEI installed, for testing/debugging
  # Run docker compose with "--profile debug" to include this container
  # If using the Makefiles, run "make <target> DEBUG=true"
  lab_terminal:
    image: ghcr.io/ad-sdl/wei
    container_name: lab_terminal
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
      - diaspora_config:/home/app/.diaspora
    entrypoint: ["/sbin/matchhostfsowner"]
    tty: true
    profiles: [debug]

################
# Data Storage #
################
volumes:
  diaspora_config:
    driver: local
