# Note: this file is included in the compose.yaml file in the root directory
#     and is not intended to be used directly.
name: squid_app

services:
  squid_app:
    container_name: squid_app
    build:
      context: .
      dockerfile: Dockerfile
    command: squid_app
    env_file: [../../.env]
    volumes:
      - ${WEI_DATA_DIR}:/home/app/.wei
    profiles: [squid_app]
