# Note: this file is included in the compose.yaml file in the root directory
#     and is not intended to be used directly.
name: squid_app

services:
  squid_app:
    image: ghcr.io/ad-sdl/squid_app
    container_name: squid_app
    build:
      context: .
      dockerfile: Dockerfile
    # command: python /home/app/squid_app/src/squid_app.py
    env_file: [../../.env]
    volumes:
      - ${WEI_DATA_DIR}:/home/app/.wei
      # - ./:/home/app/squid_app
    profiles: [squid_app]
    depends_on:
      - rpl_modular_wc_engine
      - rpl_modular_wc_server
      - rpl_redis
