equipment:
  - name: corning_96_wellplate_360ul_flat
    location: "1"
  - name: opentrons_96_tiprack_20ul #opentrons_96_tiprack_1000ul
    location: "8"
  - name: opentrons_96_tiprack_1000ul
    location: "9"
  - name: p20_single_gen2 #p1000_single_gen2
    mount: right
  - name: p1000_single_gen2
    mount: left
commands:
  - name: Make Master mix
    source: 1:[A1, A2, A3, A4]
    destination: 1:B1
    volume: [15, 100, 700, 300]

  - name: Combine forwared primers
    source: 1:[D1, D3, D3, D4, D5, D6, D7, D8]
    destination: 1:[C1, C3, C3, C4, C5, C6, C7, C8]
    volume: [13, 15, 16, 17, 19, 11, 15, 15]

  - name: Combine backeard primers
    source: 1:[E1, E3, E3, E4, E5, E6, E7, E8]
    destination: 1:[C1, C3, C3, C4, C5, C6, C7, C8]
    volume: [13, 15, 16, 17, 19, 11, 15, 15]

  - name: Combine DNA
    source: 1:[F1, F3, F3, F4, F5, F6, F7, F8]
    destination: 1:[C1, C3, C3, C4, C5, C6, C7, C8]
    volume: [13, 15, 16, 17, 19, 11, 15, 15]

metadata:
  protocolName: PCR example template
  author: Kyle khippe@anl.gov
  description: Demonstration of pcr protocol for ot2
  apiLevel: "2.12"
