# Note: this file is included in the compose.yaml file in the root directory
#     and is not intended to be used directly.
name: rpl_modular_wc
services:

###########
# Modules #
###########
  ot2_alpha_node:
    image: ghcr.io/ad-sdl/ot2_module
    container_name: ot2_alpha_node
    ports:
      - 2003:2003
    command: python3 ot2_module/src/ot2_rest_node.py --alias="ot2_alpha" --port=2003 --ot2_ip=146.137.240.101
  ot2_beta_node:
    image: ghcr.io/ad-sdl/ot2_module
    container_name: ot2_beta_node
    ports:
      - 2004:2004
    command: python3 ot2_module/src/ot2_rest_node.py --alias="ot2_beta" --port=2004 --ot2_ip=146.137.240.100
  ot2_gamma_node:
    image: ghcr.io/ad-sdl/ot2_module
    container_name: ot2_gamma_node
    ports:
      - 2005:2005
    command: python3 ot2_module/src/ot2_rest_node.py --alias="ot2_gamma" --port=2005 --ot2_ip=146.137.240.102
  ot2_delta_node:
    image: ghcr.io/ad-sdl/ot2_module
    container_name: ot2_delta_node
    ports:
      - 2006:2006
    command: python3 ot2_module/src/ot2_rest_node.py --alias="ot2_delta" --port=2006 --ot2_ip=146.137.240.103
  pf400_node:
    image: ghcr.io/ad-sdl/pf400_module
    container_name: pf400_node
    ports:
      - 3000:3000
    command: python -m pf400_rest_node --port 3000 --pf400_ip 146.137.240.35 --pf400_port 10100

#####################
# WEI Core Services #
#####################
  rpl_modular_wc_server:
    image: ghcr.io/ad-sdl/wei:v0.5.5
    container_name: rpl_modular_wc_server
    ports:
      - 8000:8000
    volumes:
      - /home/rpl/workspace/rpl_workcell/workcells:/workcell_defs
      - ../../applications/color_picker_app/protocol_files:/protocol_files
      - ../../applications/squid_app/protocols:/protocols
      - ~/.wei:/home/app/.wei
      - diaspora_config:/home/app/.diaspora
    command: python3 -m wei.server --workcell /workcell_defs/rpl_modular_workcell/rpl_modular_workcell.yaml
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    depends_on:
      - rpl_redis
  rpl_modular_wc_engine:
    image: ghcr.io/ad-sdl/wei:v0.5.5
    container_name: rpl_modular_wc_engine
    volumes:
      - /home/rpl/workspace/rpl_workcell/workcells:/workcell_defs
      - ../../applications/color_picker_app/protocol_files:/protocol_files
      - ../../applications/squid_app/protocols:/protocols
      - ~/.wei:/home/app/.wei
    command: python3 -m wei.engine --workcell /workcell_defs/rpl_modular_workcell/rpl_modular_workcell.yaml
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    depends_on:
      - rpl_redis