# Note: this file is included in the compose.yaml file in the root directory
#     and is not intended to be used directly.
name: rpl_modular_wc

#####################
# WEI Core Services #
#####################
services:
  rpl_modular_wc_server:
    image: ghcr.io/ad-sdl/wei
    container_name: rpl_modular_wc_server
    ports:
      - 8000:8000
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ../../applications/color_picker_app/protocol_files:/protocol_files
      - ${WEI_DATA_DIR}:/home/app/.wei
      - diaspora_config:/home/app/.diaspora
    command: python3 -m wei.server --workcell /workcell_defs/rpl_modular_workcell/rpl_modular_workcell.yaml --use_diaspora ${USE_DIASPORA}
    env_file: [../../.env]
    depends_on:
      - rpl_redis
  rpl_modular_wc_engine:
    image: ghcr.io/ad-sdl/wei
    container_name: rpl_modular_wc_engine
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ../../applications/color_picker_app/protocol_files:/protocol_files
      - ${WEI_DATA_DIR}:/home/app/.wei
    command: python3 -m wei.engine --workcell /workcell_defs/rpl_modular_workcell/rpl_modular_workcell.yaml --use_diaspora ${USE_DIASPORA}
    environment:
     - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
    env_file: [../../.env]
    depends_on:
      - rpl_redis
