#####################
# WEI Core Services #
#####################
# Note: this is included in the compose.yaml file in the root directory
#      and is not intended to be used directly. All relative paths are
#     relative to the root directory.
services:
  rpl_modular_wc_server:
    image: ghcr.io/ad-sdl/wei
    container_name: rpl_modular_wc_server
    ports:
      - 8000:8000
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
      - diaspora_config:/home/app/.diaspora
    command: python3 -m wei.server --workcell /workcell_defs/rpl_modular_workcell/rpl_modular_workcell.yaml --use_diaspora ${USE_DIASPORA}
    env_file: [../../.env]
  rpl_modular_wc_engine:
    image: ghcr.io/ad-sdl/wei
    container_name: rpl_modular_wc_engine
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
    command: python3 -m wei.engine --workcell /workcell_defs/rpl_modular_workcell/rpl_modular_workcell.yaml --use_diaspora ${USE_DIASPORA}
    env_file: [../../.env]
